### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by guilhermeaiolfi** [JonDum/ractive-multiselect#1]
Hi,

just to let you know that the demo page is not working: http://jondum.github.io/ractive-multiselect/demo/

I tried to test it in a jsfiddle and it seems a problem when loading the component template.

I was trying to see if using <option> works the same way that ractive-select does. I couldn't find anything in the code that tell it accepts <option>, but the readme says it does. Can you confirm that it's not yet supported in ractive-multiselect or explain to me how that magic works?

Thanks

**Comment by sarendipitee** [comment]
Oh weird. Should be fixed now. Thanks for letting me know
