### ISSUE TITLE
Typing while a tag is selected then pressing delete

### ISSUE THREAD

**Issue by Jedidiah** [JonDum/ractive-multiselect#3]
![delete-bug mov](https://cloud.githubusercontent.com/assets/113929/16902122/21dabe14-4c4d-11e6-933e-59bb5b0daf29.gif)

Issue demonstrated in the gif. With a selection in the box and focus in the textfield if you press ← it selects the tag, then if you start typing the tag remains selected and the text is entered, if you press backspace while typing it deletes the still selected tag as well as all the text in the textfield.

**Comment by sarendipitee** [comment]
Cheers. Thanks for noticing these!

**Comment by Jedidiah** [comment]
No problem, thank you for making it Jon!
